sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t westmd23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true westmd23/docker-react npm run test
